/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HotlistRouteImport } from './routes/hotlist'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardCrawlRouteImport } from './routes/dashboard/crawl'
import { Route as DashboardInboxRouteImport } from './routes/dashboard/inbox'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardPersonalizationRouteImport } from './routes/dashboard/personalization'
import { Route as DashboardPublishRouteImport } from './routes/dashboard/publish'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStudioRouteImport } from './routes/dashboard/studio'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as LoginAuthRouteImport } from './routes/login.auth'
import { Route as LoginForgotPasswordRouteImport } from './routes/login.forgot-password'
import { Route as LoginResetPasswordRouteImport } from './routes/login.reset-password'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminAuditRouteImport } from './routes/dashboard/admin/audit'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardStudioIdRouteImport } from './routes/dashboard/studio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotlistRoute = HotlistRouteImport.update({
  id: '/hotlist',
  path: '/hotlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrawlRoute = DashboardCrawlRouteImport.update({
  id: '/crawl',
  path: '/crawl',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPersonalizationRoute =
  DashboardPersonalizationRouteImport.update({
    id: '/personalization',
    path: '/personalization',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPublishRoute = DashboardPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudioRoute = DashboardStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const LoginAuthRoute = LoginAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LoginRoute,
} as any)
const LoginForgotPasswordRoute = LoginForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LoginRoute,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAuditRoute = DashboardAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudioIdRoute = DashboardStudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/hotlist': typeof HotlistRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/crawl': typeof DashboardCrawlRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/personalization': typeof DashboardPersonalizationRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/studio': typeof DashboardStudioRouteWithChildren
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/login/auth': typeof LoginAuthRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/studio/$id': typeof DashboardStudioIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/hotlist': typeof HotlistRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/crawl': typeof DashboardCrawlRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/personalization': typeof DashboardPersonalizationRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/studio': typeof DashboardStudioRouteWithChildren
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/login/auth': typeof LoginAuthRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/studio/$id': typeof DashboardStudioIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/hotlist': typeof HotlistRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/crawl': typeof DashboardCrawlRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/personalization': typeof DashboardPersonalizationRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/studio': typeof DashboardStudioRouteWithChildren
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/login/auth': typeof LoginAuthRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/studio/$id': typeof DashboardStudioIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/dashboard'
    | '/hotlist'
    | '/login'
    | '/pricing'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/crawl'
    | '/dashboard/inbox'
    | '/dashboard/logs'
    | '/dashboard/personalization'
    | '/dashboard/publish'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard/tasks'
    | '/login/auth'
    | '/login/forgot-password'
    | '/login/reset-password'
    | '/dashboard/'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/users'
    | '/dashboard/studio/$id'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/hotlist'
    | '/login'
    | '/pricing'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/crawl'
    | '/dashboard/inbox'
    | '/dashboard/logs'
    | '/dashboard/personalization'
    | '/dashboard/publish'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard/tasks'
    | '/login/auth'
    | '/login/forgot-password'
    | '/login/reset-password'
    | '/dashboard'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/users'
    | '/dashboard/studio/$id'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/dashboard'
    | '/hotlist'
    | '/login'
    | '/pricing'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/crawl'
    | '/dashboard/inbox'
    | '/dashboard/logs'
    | '/dashboard/personalization'
    | '/dashboard/publish'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard/tasks'
    | '/login/auth'
    | '/login/forgot-password'
    | '/login/reset-password'
    | '/dashboard/'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/users'
    | '/dashboard/studio/$id'
    | '/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HotlistRoute: typeof HotlistRoute
  LoginRoute: typeof LoginRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotlist': {
      id: '/hotlist'
      path: '/hotlist'
      fullPath: '/hotlist'
      preLoaderRoute: typeof HotlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crawl': {
      id: '/dashboard/crawl'
      path: '/crawl'
      fullPath: '/dashboard/crawl'
      preLoaderRoute: typeof DashboardCrawlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/personalization': {
      id: '/dashboard/personalization'
      path: '/personalization'
      fullPath: '/dashboard/personalization'
      preLoaderRoute: typeof DashboardPersonalizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/publish': {
      id: '/dashboard/publish'
      path: '/publish'
      fullPath: '/dashboard/publish'
      preLoaderRoute: typeof DashboardPublishRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio': {
      id: '/dashboard/studio'
      path: '/studio'
      fullPath: '/dashboard/studio'
      preLoaderRoute: typeof DashboardStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/login/auth': {
      id: '/login/auth'
      path: '/auth'
      fullPath: '/login/auth'
      preLoaderRoute: typeof LoginAuthRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/forgot-password': {
      id: '/login/forgot-password'
      path: '/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/reset-password': {
      id: '/login/reset-password'
      path: '/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/audit': {
      id: '/dashboard/admin/audit'
      path: '/admin/audit'
      fullPath: '/dashboard/admin/audit'
      preLoaderRoute: typeof DashboardAdminAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/$id': {
      id: '/dashboard/studio/$id'
      path: '/$id'
      fullPath: '/dashboard/studio/$id'
      preLoaderRoute: typeof DashboardStudioIdRouteImport
      parentRoute: typeof DashboardStudioRoute
    }
  }
}

interface DashboardStudioRouteChildren {
  DashboardStudioIdRoute: typeof DashboardStudioIdRoute
}

const DashboardStudioRouteChildren: DashboardStudioRouteChildren = {
  DashboardStudioIdRoute: DashboardStudioIdRoute,
}

const DashboardStudioRouteWithChildren = DashboardStudioRoute._addFileChildren(
  DashboardStudioRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCrawlRoute: typeof DashboardCrawlRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardPersonalizationRoute: typeof DashboardPersonalizationRoute
  DashboardPublishRoute: typeof DashboardPublishRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStudioRoute: typeof DashboardStudioRouteWithChildren
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminAuditRoute: typeof DashboardAdminAuditRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCrawlRoute: DashboardCrawlRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardPersonalizationRoute: DashboardPersonalizationRoute,
  DashboardPublishRoute: DashboardPublishRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStudioRoute: DashboardStudioRouteWithChildren,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminAuditRoute: DashboardAdminAuditRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LoginRouteChildren {
  LoginAuthRoute: typeof LoginAuthRoute
  LoginForgotPasswordRoute: typeof LoginForgotPasswordRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAuthRoute: LoginAuthRoute,
  LoginForgotPasswordRoute: LoginForgotPasswordRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HotlistRoute: HotlistRoute,
  LoginRoute: LoginRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
