"""Inbox — share-link download + file serve + reveal + STT + subtitles.

Front-end: ``sau_web/frontend/src/api/inbox.ts``

Transcribe / subtitles use the optional ``stable-ts`` + ``faster-whisper`` stack
(``web_runner.routes.subtitle``; install: ``uv pip install -e '.[media]'``).

Cookie handling for authenticated downloads:
  * **YouTube**: Playwright ``storage_state`` → Netscape conversion.
  * **Bilibili**: ``biliup``-format cookie array → Netscape conversion.
  * If no cookie file is found and yt-dlp returns a "sign in" error, the
    response includes ``auth_required: true`` + ``platform`` so the UI
    can show a friendly guide to configure authorization.
"""
from __future__ import annotations

import hashlib
import json as _json
import os
import re
import subprocess
import time
import uuid
from pathlib import Path
from urllib.parse import urlparse

from flask import Blueprint, Response, jsonify, request, send_from_directory

from web_runner.utils import BASE_DIR, COOKIES_DIR, INBOX_DIR, log

bp = Blueprint("inbox", __name__)

_SAFE_NAME = re.compile(r"^[\w.\- +\u4e00-\u9fff]+$")


def _safe_filename(name: str) -> str | None:
    name = (name or "").strip()
    if not name or ".." in name or "/" in name or "\\" in name:
        return None
    base = Path(name).name
    if not base or base in (".", ".."):
        return None
    # Allow slightly broader charset by sanitizing instead of rejecting.
    cleaned = re.sub(r"[^\w.\- +\u4e00-\u9fff]", "_", base)
    return cleaned or None


def _url_fingerprint(url: str) -> str:
    return hashlib.sha1(url.encode("utf-8")).hexdigest()[:10]


# ── Platform cookie helpers ───────────────────────────────────────────
# YouTube & Bilibili download sometimes requires authentication. The
# account management system stores cookies in platform-specific formats:
#
#   YouTube:     Playwright ``storage_state`` JSON (cookies/youtube_*.json)
#   Bilibili:    ``biliup``-format JSON array (cookies/bilibili_*.json)
#
# yt-dlp expects Netscape cookie format. The helpers below bridge each
# platform's format to Netscape on-the-fly.

_PLATFORM_DOMAINS: dict[str, set[str]] = {
    "youtube": {"youtube.com", "www.youtube.com", "m.youtube.com",
                 "youtu.be", "music.youtube.com"},
    "bilibili": {"bilibili.com", "www.bilibili.com",
                  "m.bilibili.com", "b23.tv"},
}


def _is_platform_url(url: str, platform: str) -> bool:
    """Check if a URL belongs to the given platform (hostname-based)."""
    domains = _PLATFORM_DOMAINS.get(platform)
    if not domains:
        return False
    try:
        host = urlparse(url).hostname or ""
        return any(d in host for d in domains)
    except Exception:
        return False


def _find_platform_cookie_file(glob_pattern: str) -> Path | None:
    """Find the most recent valid cookie file matching a glob pattern.

    Scans ``COOKIES_DIR`` for files matching ``glob_pattern``. Accepts
    both Playwright ``storage_state`` (dict with ``cookies`` key) and
    raw cookie array formats (e.g. biliup).
    Returns the most recently modified valid file, or ``None``.
    """
    if not COOKIES_DIR.is_dir():
        return None
    candidates: list[Path] = []
    for p in COOKIES_DIR.glob(glob_pattern):
        try:
            data = _json.loads(p.read_text(encoding="utf-8"))
            if isinstance(data, dict) and data.get("cookies"):
                candidates.append(p)
            elif isinstance(data, list) and len(data) > 0:
                candidates.append(p)
        except (OSError, _json.JSONDecodeError):
            continue
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def _find_youtube_cookie_file() -> Path | None:
    return _find_platform_cookie_file("youtube_*.json")


def _find_bilibili_cookie_file() -> Path | None:
    return _find_platform_cookie_file("bilibili_*.json")


def _storage_state_to_netscape_cookies(storage_state: dict) -> str:
    """Convert Playwright ``storage_state`` JSON to Netscape cookie format.

    Netscape format (``cookies.txt``) is what yt-dlp's ``cookiefile``
    option expects::

        .youtube.com	TRUE	/	TRUE	1769999999	SSID	abc123
        domain	includeSubdomain	path	httponly	expires	name	value

    Playwright ``storage_state`` has::

        {"cookies": [{"name": "SSID", "value": "abc123",
                       "domain": ".youtube.com", "path": "/",
                       "expires": 1769999999, "httpOnly": true,
                       "secure": true, "sameSite": "Lax"}],
         "origins": [...]}
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by social-auto-upload inbox"]
    cookies = storage_state.get("cookies", [])
    for c in cookies:
        domain = str(c.get("domain", ""))
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(c.get("path", "/"))
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0) or 0)
        name = str(c.get("name", ""))
        value = str(c.get("value", ""))
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)




def _write_temp_cookiefile(netscape_text: str) -> Path | None:
    """Write Netscape cookie text to a temp file for yt-dlp.

    Returns the file path, or None on failure. The caller is responsible
    for cleanup (the temp file sits in COOKIES_DIR with a ``.txt`` suffix
    and is unlinked after the download completes or on error).
    """
    try:
        path = COOKIES_DIR / f"_ytdlp_temp_{uuid.uuid4().hex[:12]}.txt"
        path.write_text(netscape_text, encoding="utf-8")
        return path
    except OSError:
        return None


def _needs_auth_download(error_message: str) -> bool:
    """Check if a yt-dlp error is due to missing authentication.

    Returns True if the error mentions sign-in, login, bot detection,
    or cookie requirements.
    """
    if not error_message:
        return False
    lowered = error_message.lower()
    triggers = [
        "sign in to confirm",
        "sign in",
        "login required",
        "authentication required",
        "this video requires",
        "you need to sign in",
        "cookies",
        "bot",
        "private video",
        "age-gate",
        "age restricted",
    ]
    return any(t in lowered for t in triggers)


@bp.post("/api/inbox/download")
def inbox_download():
    payload = request.get_json(silent=True) or {}
    url = (payload.get("url") or "").strip()
    if not url:
        return jsonify({"success": False, "message": "url is required"}), 400
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        return jsonify({"success": False, "message": "invalid url"}), 400

    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d_%H%M%S")
    fp = _url_fingerprint(url)
    # Restrict filenames for shell safety; keep title readable.
    outtmpl = str(INBOX_DIR / f"%(title).60s_{ts}_{fp}.%(ext)s")

    try:
        import yt_dlp  # type: ignore
    except ImportError:
        return jsonify({
            "success": False,
            "message": "yt-dlp not installed; run: uv pip install yt-dlp",
        }), 503

    # ── Platform cookie auto-detection ──────────────────────────────
    # Detect the platform from the URL and look for existing account
    # cookies, converting to Netscape format for yt-dlp automatically.
    cookiefile_path: Path | None = None
    cookie_src: Path | None = None
    download_platform: str | None = None

    if _is_platform_url(url, "youtube"):
        download_platform = "youtube"
        cookie_src = _find_youtube_cookie_file()
        if cookie_src is not None:
            try:
                storage_state = _json.loads(cookie_src.read_text(encoding="utf-8"))
                netscape = _storage_state_to_netscape_cookies(storage_state)
                cookiefile_path = _write_temp_cookiefile(netscape)
                if cookiefile_path:
                    log(f"[inbox] using YouTube cookies from {cookie_src.name}")
            except (OSError, _json.JSONDecodeError) as exc:
                log(f"[inbox] failed to read YouTube cookies {cookie_src.name}: {exc}")

    if _is_platform_url(url, "bilibili"):
        download_platform = "bilibili"
        cookie_src = _find_bilibili_cookie_file()
        if cookie_src is not None:
            try:
                raw = _json.loads(cookie_src.read_text(encoding="utf-8"))
                # biliup format: JSON array → storage_state via upstream converter
                if isinstance(raw, list):
                    # Reuse the authoritative biliup→storage_state converter from
                    # uploader. It only uses json + pathlib; no patchright deps.
                    try:
                        from uploader.bilibili_uploader.note import \
                            _convert_biliup_cookies_to_storage_state as _biliup_to_ss
                        storage_state = _biliup_to_ss(str(cookie_src))
                    except ImportError:
                        # Fallback: inline conversion
                        storage_state = {
                            "cookies": raw,
                            "origins": [{
                                "origin": "https://member.bilibili.com",
                                "localStorage": [],
                            }],
                        }
                    netscape = _storage_state_to_netscape_cookies(storage_state)
                elif isinstance(raw, dict) and raw.get("cookies"):
                    netscape = _storage_state_to_netscape_cookies(raw)
                else:
                    netscape = None
                if netscape:
                    cookiefile_path = _write_temp_cookiefile(netscape)
                    if cookiefile_path:
                        log(f"[inbox] using Bilibili cookies from {cookie_src.name}")
            except (OSError, _json.JSONDecodeError) as exc:
                log(f"[inbox] failed to read Bilibili cookies {cookie_src.name}: {exc}")

    ydl_opts: dict = {
        "outtmpl": outtmpl,
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "restrictfilenames": True,
        "retries": 3,
        "fragment_retries": 3,
        "socket_timeout": 60,
        "ignoreerrors": False,
        # Prefer a single progressive file when possible.
        "format": "bv*+ba/b",
        "merge_output_format": "mp4",
    }
    if cookiefile_path is not None:
        ydl_opts["cookiefile"] = str(cookiefile_path)

    _temp_cookiefile = cookiefile_path

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            if info is None:
                return jsonify({"success": False, "message": "extractor returned empty info"}), 502
            # playlist → take first entry
            if info.get("_type") == "playlist" and info.get("entries"):
                entries = [e for e in info["entries"] if e]
                info = entries[0] if entries else info
            filename = ydl.prepare_filename(info)
            # after merge, ext may be mp4
            path = Path(filename)
            if not path.exists():
                alt = path.with_suffix(".mp4")
                if alt.exists():
                    path = alt
        if not path.exists():
            candidates = sorted(
                INBOX_DIR.glob(f"*_{ts}_{fp}.*"),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
            if not candidates:
                candidates = sorted(
                    INBOX_DIR.glob(f"*_{ts}_*"),
                    key=lambda p: p.stat().st_mtime,
                    reverse=True,
                )
            if not candidates:
                return jsonify({"success": False, "message": "download finished but file missing"}), 502
            path = candidates[0]

        # Normalize weird characters for subsequent /file/<name> fetches
        safe = _safe_filename(path.name) or path.name
        final = INBOX_DIR / safe
        if final != path:
            try:
                if final.exists():
                    final.unlink()
                path.rename(final)
                path = final
            except OSError:
                path = path  # keep original

        # Cleanup temp cookiefile on success
        if _temp_cookiefile is not None and _temp_cookiefile.is_file():
            try:
                _temp_cookiefile.unlink()
            except OSError:
                pass

        size = path.stat().st_size if path.exists() else 0
        log(f"[inbox] downloaded {path.name} ({size} bytes) from {url}")
        return jsonify({
            "success": True,
            "filename": path.name,
            "engine": "yt-dlp",
            "dir": str(INBOX_DIR),
            "size": size,
            "data": {
                "filename": path.name,
                "engine": "yt-dlp",
                "dir": str(INBOX_DIR),
                "size": size,
                "title": (info or {}).get("title") if isinstance(info, dict) else None,
            },
        })
    except Exception as exc:  # strict-exceptions: allow boundary
        exc_msg = f"{type(exc).__name__}: {exc}"
        log(f"[inbox] download failed: {exc_msg}")

        # Check if this is an auth-required error
        auth_required = download_platform is not None and _needs_auth_download(str(exc))

        if auth_required and cookie_src is not None:
            # Has cookie file but still auth failed → cookies may be expired
            user_msg = (
                f"{download_platform.title()} 需要登录验证。当前已配置的 Cookie 可能已过期，"
                f"请前往「账号管理」重新授权 {download_platform.title()} 账号后重试。"
            )
        elif auth_required:
            if download_platform == "youtube":
                user_msg = (
                    "YouTube 需要登录验证才能下载此视频。"
                    "请先前往「账号管理」配置 YouTube 账号授权（扫码/登录 YouTube Studio），"
                    "完成后即可自动使用 Cookie 下载。"
                )
            elif download_platform == "bilibili":
                user_msg = (
                    "Bilibili 需要登录验证才能下载此视频（大会员内容/区域限制）。"
                    "请先前往「账号管理」配置 Bilibili 账号授权（扫码登录），"
                    "完成后即可自动使用 Cookie 下载。"
                )
            else:
                user_msg = f"{download_platform.title()} 需要登录验证才能下载此视频。"
        else:
            user_msg = f"下载失败：{exc}"

        body: dict = {
            "success": False,
            "message": user_msg,
        }
        if auth_required:
            body["auth_required"] = True
            body["platform"] = download_platform

        return jsonify(body), 502
    finally:
        # Always clean up temp cookiefile if it exists
        if _temp_cookiefile is not None and _temp_cookiefile.is_file():
            try:
                _temp_cookiefile.unlink()
            except OSError:
                pass


@bp.post("/api/inbox/organize")
def inbox_organize():
    """Copy selected inbox files into a date-based subdirectory for batch
    organization. Replaces the old download-zip endpoint.

    Request JSON::

        { "filenames": ["video1.mp4", "video2.mp4"] }

    Response::

        {
          "success": true,
          "message": "已归档 3 个文件到 下载组_2026-07-28",
          "data": {
            "dirname": "下载组_2026-07-28",
            "count": 3,
            "path": "/path/to/inbox/下载组_2026-07-28"
          }
        }
    """
    import shutil

    payload = request.get_json(silent=True) or {}
    filenames: list[str] = []
    raw_list = payload.get("filenames") or payload.get("files") or []
    if isinstance(raw_list, list):
        filenames = [str(x) for x in raw_list if x]

    if not filenames:
        return jsonify({"success": False, "message": "filenames required"}), 400

    # Deduplicate while preserving order
    seen: set[str] = set()
    uniq: list[str] = []
    for n in filenames:
        if n not in seen:
            seen.add(n)
            uniq.append(n)

    if len(uniq) > 50:
        return jsonify({"success": False, "message": "最多同时归档 50 个文件"}), 400

    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    resolved: list[tuple[str, Path]] = []
    missing: list[str] = []

    for raw in uniq:
        name = raw.strip()
        safe = _safe_filename(name)
        if not safe:
            missing.append(name)
            continue
        path = INBOX_DIR / safe
        if not path.is_file():
            matches = list(INBOX_DIR.glob(f"*{Path(name).name}"))
            if matches:
                path = matches[0]
            else:
                missing.append(name)
                continue
        resolved.append((path.name, path))

    if not resolved:
        return jsonify({"success": False, "message": "没有可归档的文件"}), 404

    # Create date-based group directory
    date_str = time.strftime("%Y-%m-%d")
    group_dir = INBOX_DIR / f"\u4e0b\u8f7d\u7ec4_{date_str}"
    group_dir.mkdir(parents=True, exist_ok=True)

    copied = 0
    errors: list[str] = []
    for arcname, src in resolved:
        dst = group_dir / arcname
        try:
            if dst.exists():
                stem = Path(arcname).stem
                ext = Path(arcname).suffix
                dst = group_dir / f"{stem}_{uuid.uuid4().hex[:4]}{ext}"
            shutil.copy2(str(src), str(dst))
            copied += 1
        except OSError as exc:
            errors.append(f"{arcname}: {exc}")

    log(f"[inbox] organize: {copied} files -> {group_dir.name}")
    if missing:
        log(f"[inbox] organize missing: {missing}")
    if errors:
        log(f"[inbox] organize errors: {errors}")

    msg = f"\u5df2\u5f52\u6863 {copied} \u4e2a\u6587\u4ef6\u5230 {group_dir.name}"
    if errors:
        msg += f"\uff0c{len(errors)} \u4e2a\u5931\u8d25"

    return jsonify({
        "success": True,
        "message": msg,
        "data": {
            "dirname": group_dir.name,
            "count": copied,
            "path": str(group_dir),
        },
    })


@bp.get("/api/inbox/file/<path:filename>")
def inbox_file(filename: str):
    """Serve an inbox media file (inline). Supports Range for video seek/preview."""
    safe = _safe_filename(filename)
    if not safe:
        return jsonify({"success": False, "message": "invalid filename"}), 400
    path = INBOX_DIR / safe
    # also try original if sanitization changed nothing but file uses other name
    if not path.is_file():
        # fuzzy: match suffix fingerprint / basename
        matches = list(INBOX_DIR.glob(f"*{Path(filename).name}"))
        if matches:
            path = matches[0]
            safe = path.name
        else:
            return jsonify({"success": False, "message": "file not found"}), 404
    # conditional=True enables Range / If-None-Match so the browser can seek
    # without downloading the entire file for cover + preview playback.
    resp = send_from_directory(
        INBOX_DIR,
        safe,
        as_attachment=False,
        conditional=True,
        max_age=0,
    )
    resp.headers["Accept-Ranges"] = "bytes"
    # Allow canvas frame capture when UI is served from a different origin
    # (e.g. Vite :5174 → API :6001 without proxy).
    resp.headers["Access-Control-Allow-Origin"] = request.headers.get("Origin") or "*"
    resp.headers["Access-Control-Allow-Credentials"] = "true"
    return resp


@bp.get("/api/inbox/list")
def inbox_list():
    """List downloaded files for the inbox UI."""
    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    files = []
    for p in sorted(INBOX_DIR.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True):
        if not p.is_file() or p.name.startswith("."):
            continue
        st = p.stat()
        files.append({
            "filename": p.name,
            "size": st.st_size,
            "mtime": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(st.st_mtime)),
        })
    return jsonify({"success": True, "data": files})


def _unlink_quiet(path: Path) -> bool:
    try:
        if path.is_file():
            path.unlink()
            return True
    except OSError as exc:
        log(f"[inbox] unlink failed {path.name}: {exc}")
    return False


def _delete_inbox_artifacts(
    filenames: list[str],
    *,
    srt_filenames: list[str] | None = None,
) -> dict:
    """Delete inbox videos (+ optional burned outputs) and related SRT files.

    Returns ``{deleted: [...], missing: [...], srt_deleted: [...]}``.
    """
    from web_runner.routes.subtitle import SUB_DIR

    deleted: list[str] = []
    missing: list[str] = []
    srt_deleted: list[str] = []
    stems: set[str] = set()

    for raw in filenames:
        name = (raw or "").strip()
        if not name:
            continue
        safe = _safe_filename(name)
        if not safe:
            missing.append(name)
            continue
        path = INBOX_DIR / safe
        if not path.is_file():
            # fuzzy basename match
            matches = list(INBOX_DIR.glob(f"*{Path(name).name}"))
            if matches:
                path = matches[0]
                safe = path.name
            else:
                missing.append(name)
                continue
        if _unlink_quiet(path):
            deleted.append(safe)
            stems.add(Path(safe).stem)
            log(f"[inbox] deleted file {safe}")
        else:
            missing.append(name)

    # Explicit SRT names from the client (if known)
    for raw in srt_filenames or []:
        sname = Path((raw or "").strip()).name
        if not sname or ".." in sname:
            continue
        sp = SUB_DIR / sname
        if _unlink_quiet(sp):
            srt_deleted.append(sname)

    # Also sweep SRTs that share a stem with deleted videos
    # e.g. video.mp4 → video_zh_abc.srt / video_bilingual_xyz.srt
    if stems and SUB_DIR.is_dir():
        for srt in list(SUB_DIR.iterdir()):
            if not srt.is_file() or not srt.name.endswith(".srt"):
                continue
            for stem in stems:
                if srt.name.startswith(stem + "_") or srt.stem == stem:
                    if _unlink_quiet(srt) and srt.name not in srt_deleted:
                        srt_deleted.append(srt.name)
                    break

    return {
        "deleted": deleted,
        "missing": missing,
        "srt_deleted": srt_deleted,
    }


@bp.post("/api/inbox/delete")
def inbox_delete():
    """Permanently delete one or more inbox files from disk.

    Request JSON::

        { "filename": "a.mp4" }
        { "filenames": ["a.mp4", "b.mp4"], "srt_filenames": ["a_zh_xxx.srt"] }
    """
    payload = request.get_json(silent=True) or {}
    filenames: list[str] = []
    if payload.get("filename"):
        filenames.append(str(payload["filename"]))
    raw_list = payload.get("filenames") or []
    if isinstance(raw_list, list):
        filenames.extend(str(x) for x in raw_list if x)

    # Deduplicate while preserving order
    seen: set[str] = set()
    uniq: list[str] = []
    for n in filenames:
        if n not in seen:
            seen.add(n)
            uniq.append(n)

    if not uniq:
        return jsonify({"success": False, "message": "请指定要删除的文件"}), 400

    srt_raw = payload.get("srt_filenames") or []
    srt_list = [str(x) for x in srt_raw] if isinstance(srt_raw, list) else []

    result = _delete_inbox_artifacts(uniq, srt_filenames=srt_list)
    # Treat "already gone" as success so UI can clear the row cleanly.
    if not result["deleted"] and result["missing"] and not result["srt_deleted"]:
        return jsonify({
            "success": True,
            "message": "文件已不存在，已从列表移除",
            "data": result,
        })
    return jsonify({
        "success": True,
        "message": f"已删除 {len(result['deleted'])} 个文件",
        "data": result,
    })


@bp.post("/api/inbox/clear")
def inbox_clear():
    """Permanently delete all files in the inbox directory (+ related SRTs)."""
    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    names = [
        p.name for p in INBOX_DIR.iterdir()
        if p.is_file() and not p.name.startswith(".")
    ]
    result = _delete_inbox_artifacts(names)
    # Also wipe leftover subtitle files that may not match remaining stems
    try:
        from web_runner.routes.subtitle import SUB_DIR
        if SUB_DIR.is_dir():
            for srt in list(SUB_DIR.iterdir()):
                if srt.is_file() and srt.suffix.lower() == ".srt":
                    if _unlink_quiet(srt) and srt.name not in result["srt_deleted"]:
                        result["srt_deleted"].append(srt.name)
    except Exception as exc:
        log(f"[inbox] clear srt sweep: {exc}")

    log(f"[inbox] clear all: deleted={len(result['deleted'])} srt={len(result['srt_deleted'])}")
    return jsonify({
        "success": True,
        "message": f"已清空下载目录（{len(result['deleted'])} 个文件）",
        "data": result,
    })


@bp.post("/api/inbox/reveal")
def inbox_reveal():
    """Open downloads folder in OS file manager (best-effort)."""
    payload = request.get_json(silent=True) or {}
    filename = payload.get("filename")
    target = INBOX_DIR
    if filename:
        safe = _safe_filename(str(filename))
        if safe and (INBOX_DIR / safe).is_file():
            target = INBOX_DIR / safe
    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    try:
        system = os.uname().sysname if hasattr(os, "uname") else ""
        if system == "Darwin":
            subprocess.Popen(["open", str(target if target.is_dir() else target.parent)])
        elif system == "Linux":
            subprocess.Popen(["xdg-open", str(target if target.is_dir() else target.parent)])
        else:
            os.startfile(str(target if target.is_dir() else target.parent))  # type: ignore[attr-defined]
        return jsonify({"success": True, "message": "opened", "path": str(target)})
    except Exception as exc:  # strict-exceptions: allow
        return jsonify({"success": False, "message": str(exc)}), 500


@bp.post("/api/inbox/transcribe")
def inbox_transcribe():
    """Stream plain-text transcript for an inbox video via faster-whisper.

    Request JSON: ``{ "filename": "...", "language": "zh"|null }``
    Response: ``text/plain`` stream of recognized text (segment by segment).

    Requires optional media extras + ffmpeg on PATH::

        uv pip install -e '.[media]'

    Env:
      * ``SAU_WHISPER_MODEL`` — model size (default ``base``; also tiny/small/medium…)
    """
    payload = request.get_json(silent=True) or {}
    filename = payload.get("filename") or ""
    language = (payload.get("language") or "").strip() or None

    safe = _safe_filename(str(filename))
    if not safe:
        return jsonify({"success": False, "message": "无效的文件名"}), 400

    path = INBOX_DIR / safe
    if not path.is_file():
        # fuzzy match (same as /file/)
        matches = list(INBOX_DIR.glob(f"*{Path(filename).name}"))
        if matches:
            path = matches[0]
        else:
            return jsonify({"success": False, "message": "文件不存在，请先完成下载"}), 404

    # Reuse subtitle stack (lazy import so inbox works without media extras).
    try:
        from web_runner.routes.subtitle import (
            _deps_ok,
            _extract_audio,
            _get_model,
            _has_audio_stream,
        )
    except Exception as exc:  # pragma: no cover — import-time failure
        return jsonify({
            "success": False,
            "message": f"转写模块不可用: {exc}",
        }), 501

    ok, msg = _deps_ok()
    if not ok:
        return jsonify({
            "success": False,
            "message": (
                "转写功能需要安装语音识别依赖。\n"
                "请在项目根目录执行：\n"
                "  uv pip install -e '.[media]'\n"
                "然后重启后端（python run.py）。\n"
                "另需本机已安装 ffmpeg（macOS: brew install ffmpeg）。"
            ),
        }), 501

    # Fail fast before opening a stream when the file has no audio track.
    if not _has_audio_stream(path):
        return jsonify({
            "success": False,
            "message": "视频没有音轨，无法转写文案。请换一个带人声/旁白的视频。",
        }), 400

    # Capture path/lang in closure for the generator.
    video_path = path
    lang_hint = language

    def generate():
        audio = None
        try:
            log(f"[inbox] transcribe start {video_path.name}")
            # Explicit WAV extract keeps STT input predictable (16 kHz mono).
            audio = _extract_audio(video_path)
            model = _get_model()
            kwargs: dict = {
                "beam_size": 5,
                "vad_filter": True,
            }
            if lang_hint:
                kwargs["language"] = lang_hint
            segments, info = model.transcribe(str(audio), **kwargs)
            detected = getattr(info, "language", None)
            log(
                f"[inbox] transcribe running lang={detected or lang_hint or 'auto'} "
                f"file={video_path.name}"
            )
            n = 0
            for seg in segments:
                text = (getattr(seg, "text", None) or "").strip()
                if not text:
                    continue
                n += 1
                # Stream segment text; newline between segments reads better in UI.
                yield text + "\n"
            if n == 0:
                yield "（未识别到有效语音内容，请确认视频含人声）\n"
            log(f"[inbox] transcribe done {video_path.name} segments={n}")
        except FileNotFoundError as exc:
            # ffmpeg / ffprobe missing
            log(f"[inbox] transcribe missing tool: {exc}")
            yield (
                "转写失败：未找到 ffmpeg。\n"
                "macOS 安装：brew install ffmpeg\n"
                "安装后重启后端再试。\n"
            )
        except Exception as exc:  # strict-exceptions: allow boundary
            log(f"[inbox] transcribe failed: {type(exc).__name__}: {exc}")
            yield f"转写失败：{exc}\n"
        finally:
            if audio is not None:
                try:
                    Path(audio).unlink(missing_ok=True)
                except OSError:
                    pass

    return Response(
        generate(),
        mimetype="text/plain; charset=utf-8",
        headers={
            # Long videos can take minutes; discourage intermediary buffering.
            "X-Accel-Buffering": "no",
            "Cache-Control": "no-cache",
        },
    )


def _resolve_inbox_video(filename: str) -> Path | None:
    safe = _safe_filename(str(filename))
    if not safe:
        return None
    path = INBOX_DIR / safe
    if path.is_file():
        return path
    matches = list(INBOX_DIR.glob(f"*{Path(filename).name}"))
    return matches[0] if matches else None


@bp.post("/api/inbox/subtitle")
def inbox_subtitle():
    """Generate (and optionally burn-in) subtitles with NDJSON progress stream.

    Request JSON::

        {
          "filename": "video.mp4",
          "mode": "bilingual" | "zh" | "en" | "source",
          "burn": true,
          "burn_style": "auto" | "hard" | "soft",
          "quality": "original" | "1080" | "720"
        }

    Response: ``application/x-ndjson`` lines::

        {"type":"progress","phase":"extract","pct":10,"label":"…"}
        {"type":"done","data":{…}}
        {"type":"error","message":"…"}
    """
    import json as _json

    payload = request.get_json(silent=True) or {}
    filename = payload.get("filename") or ""
    mode = (payload.get("mode") or payload.get("lang") or "bilingual").strip().lower()
    burn = payload.get("burn", True)
    if isinstance(burn, str):
        burn = burn.lower() in ("1", "true", "yes", "on")
    burn_style = (payload.get("burn_style") or payload.get("style") or "auto").strip().lower()
    if burn_style not in ("auto", "hard", "soft"):
        burn_style = "auto"
    quality = (payload.get("quality") or "1080").strip().lower()

    path = _resolve_inbox_video(filename)
    if path is None:
        return jsonify({"success": False, "message": "文件不存在，请先完成下载"}), 404

    try:
        from web_runner.routes.subtitle import (
            SUB_DIR,
            _deps_ok,
            _extract_audio,
            _has_audio_stream,
            build_subtitle_tracks,
            burn_srt_onto_video,
        )
    except Exception as exc:
        return jsonify({"success": False, "message": f"字幕模块不可用: {exc}"}), 501

    ok, msg = _deps_ok()
    if not ok:
        return jsonify({
            "success": False,
            "message": (
                "添加字幕需要语音识别依赖。\n"
                "请执行：uv pip install -e '.[media]'\n"
                "并确保本机已安装 ffmpeg。"
            ),
        }), 501

    if not _has_audio_stream(path):
        return jsonify({
            "success": False,
            "message": "视频没有音轨，无法添加字幕。",
        }), 400

    video_path = path

    def generate():
        audio = None
        try:
            def emit(obj: dict):
                return _json.dumps(obj, ensure_ascii=False) + "\n"

            yield emit({"type": "progress", "phase": "extract", "pct": 8, "label": "提取音频…"})
            log(f"[inbox] subtitle start {video_path.name} mode={mode} burn={burn} q={quality}")
            audio = _extract_audio(video_path)

            progress_buf: list[tuple[str, int, str]] = []

            def on_progress(phase: str, pct: int, label: str) -> None:
                progress_buf.append((phase, pct, label))

            # Run track build (progress collected then flushed — whisper is sync)
            srt_text, _segs, detected, meta = build_subtitle_tracks(
                audio, mode, on_progress=on_progress,
            )
            for phase, pct, label in progress_buf:
                yield emit({"type": "progress", "phase": phase, "pct": pct, "label": label})

            SUB_DIR.mkdir(parents=True, exist_ok=True)
            tag = re.sub(r"[^a-z0-9_-]+", "", mode) or "sub"
            srt_name = f"{video_path.stem}_{tag}_{uuid.uuid4().hex[:8]}.srt"
            srt_path = SUB_DIR / srt_name
            srt_path.write_text(srt_text, encoding="utf-8")
            yield emit({"type": "progress", "phase": "compose", "pct": 88, "label": "字幕文件已写入…"})

            burned_name = None
            burned_url = None
            burn_method = None
            if burn:
                yield emit({
                    "type": "progress",
                    "phase": "burn",
                    "pct": 92,
                    "label": "写入视频（硬烧录可能需数分钟）…",
                })
                burned_name = f"{video_path.stem}_sub_{tag}.mp4"
                burned_path = INBOX_DIR / burned_name
                if burned_path.exists():
                    burned_name = f"{video_path.stem}_sub_{tag}_{uuid.uuid4().hex[:6]}.mp4"
                    burned_path = INBOX_DIR / burned_name
                _, burn_method = burn_srt_onto_video(
                    video_path,
                    srt_path,
                    burned_path,
                    lang=mode,
                    style=burn_style,
                    quality=quality,
                )
                burned_url = f"/api/inbox/file/{burned_name}"
                log(f"[inbox] subtitle attached → {burned_name} method={burn_method}")

            yield emit({"type": "progress", "phase": "done", "pct": 100, "label": "完成"})
            log(f"[inbox] subtitle done {video_path.name} mode={mode} lang={detected}")
            yield emit({
                "type": "done",
                "data": {
                    "mode": mode,
                    "detected_language": detected,
                    "meta": meta,
                    "srt_filename": srt_name,
                    "srt_url": f"/api/subtitle/file/{srt_name}",
                    "srt_text": srt_text,
                    "burned_filename": burned_name,
                    "burned_url": burned_url,
                    "burn_method": burn_method,
                    "quality": quality,
                },
            })
        except Exception as exc:  # strict-exceptions: allow boundary
            log(f"[inbox] subtitle failed: {type(exc).__name__}: {exc}")
            yield _json.dumps({
                "type": "error",
                "message": f"添加字幕失败：{exc}",
            }, ensure_ascii=False) + "\n"
        finally:
            if audio is not None:
                try:
                    Path(audio).unlink(missing_ok=True)
                except OSError:
                    pass

    return Response(
        generate(),
        mimetype="application/x-ndjson; charset=utf-8",
        headers={
            "X-Accel-Buffering": "no",
            "Cache-Control": "no-cache",
        },
    )


@bp.get("/api/inbox/thumb/<path:filename>")
def inbox_thumb(filename: str):
    """JPEG cover frame for list thumbnails (cached under media/thumbs)."""
    path = _resolve_inbox_video(filename)
    if path is None:
        return jsonify({"success": False, "message": "file not found"}), 404

    thumbs = BASE_DIR / "media" / "thumbs"
    thumbs.mkdir(parents=True, exist_ok=True)
    # Cache key includes mtime so re-downloads refresh
    mtime = int(path.stat().st_mtime)
    out = thumbs / f"{path.stem}_{mtime}.jpg"
    if not out.is_file():
        # Sweep old thumbs for same stem
        for old in thumbs.glob(f"{path.stem}_*.jpg"):
            _unlink_quiet(old)
        try:
            from web_runner.routes.subtitle import _resolve_ffmpeg
            ff = _resolve_ffmpeg(prefer_libass=False)
        except Exception:
            ff = "ffmpeg"
        cmd = [
            ff, "-y",
            "-ss", "1",
            "-i", str(path),
            "-frames:v", "1",
            "-vf", "scale=480:-2",
            "-q:v", "4",
            str(out),
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if proc.returncode != 0 or not out.is_file():
            # retry without seek
            cmd2 = [
                ff, "-y", "-i", str(path),
                "-frames:v", "1", "-vf", "scale=480:-2", "-q:v", "5",
                str(out),
            ]
            proc2 = subprocess.run(cmd2, capture_output=True, text=True, timeout=120)
            if proc2.returncode != 0 or not out.is_file():
                return jsonify({"success": False, "message": "无法生成封面"}), 500
    return send_from_directory(thumbs, out.name, mimetype="image/jpeg", max_age=86400)


@bp.get("/api/inbox/storage")
def inbox_storage():
    """Disk usage for inbox + subtitles + thumbs."""
    from web_runner.routes.subtitle import SUB_DIR

    def _dir_stats(d: Path) -> dict:
        total = 0
        count = 0
        oldest = None
        newest = None
        if d.is_dir():
            for p in d.iterdir():
                if not p.is_file() or p.name.startswith("."):
                    continue
                st = p.stat()
                total += st.st_size
                count += 1
                oldest = st.st_mtime if oldest is None else min(oldest, st.st_mtime)
                newest = st.st_mtime if newest is None else max(newest, st.st_mtime)
        return {
            "bytes": total,
            "count": count,
            "oldest": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(oldest)) if oldest else None,
            "newest": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(newest)) if newest else None,
        }

    thumbs = BASE_DIR / "media" / "thumbs"
    inbox = _dir_stats(INBOX_DIR)
    subs = _dir_stats(SUB_DIR)
    th = _dir_stats(thumbs)
    return jsonify({
        "success": True,
        "data": {
            "inbox": inbox,
            "subtitles": subs,
            "thumbs": th,
            "total_bytes": inbox["bytes"] + subs["bytes"] + th["bytes"],
        },
    })


@bp.post("/api/inbox/cleanup")
def inbox_cleanup():
    """Delete inbox files older than N days. Optionally keep subtitled outputs.

    JSON: ``{ "older_than_days": 7, "keep_subtitled": true }``
    """
    payload = request.get_json(silent=True) or {}
    days = int(payload.get("older_than_days") or 7)
    keep_sub = payload.get("keep_subtitled", True)
    if isinstance(keep_sub, str):
        keep_sub = keep_sub.lower() in ("1", "true", "yes", "on")
    days = max(0, min(days, 3650))
    cutoff = time.time() - days * 86400

    to_delete: list[str] = []
    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    for p in INBOX_DIR.iterdir():
        if not p.is_file() or p.name.startswith("."):
            continue
        if p.stat().st_mtime >= cutoff:
            continue
        if keep_sub and ("_sub_" in p.stem or p.stem.endswith("_sub")):
            continue
        to_delete.append(p.name)

    result = _delete_inbox_artifacts(to_delete)
    # stale thumbs
    thumbs = BASE_DIR / "media" / "thumbs"
    thumb_deleted = 0
    if thumbs.is_dir():
        for t in list(thumbs.iterdir()):
            if t.is_file() and t.stat().st_mtime < cutoff:
                if _unlink_quiet(t):
                    thumb_deleted += 1
    result["thumbs_deleted"] = thumb_deleted
    return jsonify({
        "success": True,
        "message": f"已清理 {len(result['deleted'])} 个过期文件",
        "data": result,
    })


@bp.post("/api/inbox/subtitle/save")
def inbox_subtitle_save():
    """Save edited SRT text and optionally re-burn onto video.

    JSON: ``{ "filename": "video.mp4", "srt_text": "…", "burn": true,
              "burn_style": "hard", "quality": "1080", "mode": "bilingual" }``
    """
    payload = request.get_json(silent=True) or {}
    filename = payload.get("filename") or ""
    srt_text = payload.get("srt_text")
    if srt_text is None:
        return jsonify({"success": False, "message": "缺少 srt_text"}), 400
    srt_text = str(srt_text)
    burn = payload.get("burn", False)
    if isinstance(burn, str):
        burn = burn.lower() in ("1", "true", "yes", "on")
    burn_style = (payload.get("burn_style") or "hard").strip().lower()
    quality = (payload.get("quality") or "1080").strip().lower()
    mode = (payload.get("mode") or "source").strip().lower()

    path = _resolve_inbox_video(filename)
    if path is None:
        return jsonify({"success": False, "message": "文件不存在"}), 404

    try:
        from web_runner.routes.subtitle import SUB_DIR, burn_srt_onto_video
    except Exception as exc:
        return jsonify({"success": False, "message": str(exc)}), 501

    SUB_DIR.mkdir(parents=True, exist_ok=True)
    tag = re.sub(r"[^a-z0-9_-]+", "", mode) or "edit"
    srt_name = f"{path.stem}_{tag}_{uuid.uuid4().hex[:8]}.srt"
    srt_path = SUB_DIR / srt_name
    srt_path.write_text(srt_text, encoding="utf-8")

    burned_name = None
    burned_url = None
    burn_method = None
    if burn:
        burned_name = f"{path.stem}_sub_{tag}.mp4"
        burned_path = INBOX_DIR / burned_name
        if burned_path.exists():
            burned_name = f"{path.stem}_sub_{tag}_{uuid.uuid4().hex[:6]}.mp4"
            burned_path = INBOX_DIR / burned_name
        try:
            _, burn_method = burn_srt_onto_video(
                path, srt_path, burned_path, lang=mode, style=burn_style, quality=quality,
            )
            burned_url = f"/api/inbox/file/{burned_name}"
        except Exception as exc:
            return jsonify({"success": False, "message": f"保存字幕成功，但烧录失败：{exc}"}), 500

    return jsonify({
        "success": True,
        "data": {
            "srt_filename": srt_name,
            "srt_url": f"/api/subtitle/file/{srt_name}",
            "srt_text": srt_text,
            "burned_filename": burned_name,
            "burned_url": burned_url,
            "burn_method": burn_method,
        },
    })
